package orchestrator

// Generation of the event schema and its documentation table. Never
// hand-edit the outputs; run `go run ./cmd/gen-schemas` and commit what it
// writes.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/invopop/jsonschema"
)

// TelemetrySchemaDir is where the generated event artifacts are committed,
// relative to the repo root. They live under shared/ because humans and
// agents read them from the installed framework content.
const TelemetrySchemaDir = "shared/schemas/telemetry"

// The generated file names.
const (
	RunEventSchemaFile = "run-event.schema.json"
	RunEventTableFile  = "run-event-types.md"
)

// GenerateEventSchema renders the JSON Schema for one timeline event, with
// `kind` constrained to the vocabulary. Deterministic: the same enum always
// produces byte-identical output, which is what makes the committed copy
// checkable.
func GenerateEventSchema() ([]byte, error) {
	reflector := &jsonschema.Reflector{ExpandedStruct: true, DoNotReference: true}
	schema := reflector.Reflect(&Event{})
	if err := constrainKind(schema); err != nil {
		return nil, err
	}
	var rendered bytes.Buffer
	encoder := json.NewEncoder(&rendered)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(schema); err != nil {
		return nil, fmt.Errorf("render event schema: %w", err)
	}
	return rendered.Bytes(), nil
}

// constrainKind narrows the `kind` property to the vocabulary, so an event
// carrying a type nothing emits fails validation rather than passing as a
// plain string.
func constrainKind(schema *jsonschema.Schema) error {
	property, ok := schema.Properties.Get("kind")
	if !ok {
		return fmt.Errorf("event schema has no %q property — the struct tag changed", "kind")
	}
	for _, kind := range EventKindStrings() {
		property.Enum = append(property.Enum, kind)
	}
	return nil
}

// GenerateEventTable renders the documentation table from the same
// vocabulary the schema comes from. Two hand-maintained lists is how the
// contradiction this replaces was possible.
func GenerateEventTable() []byte {
	var out strings.Builder
	out.WriteString(eventTableHeader)
	for _, doc := range EventVocabulary() {
		fmt.Fprintf(&out, "| `%s` | %s | %s | %s |\n",
			doc.Kind, doc.Summary, fieldList(doc.Fields), doc.Roadmap)
	}
	return []byte(out.String())
}

func fieldList(fields []string) string {
	if len(fields) == 0 {
		return "—"
	}
	return "`" + strings.Join(fields, "`, `") + "`"
}

const eventTableHeader = `<!-- GENERATED by ` + "`go run ./cmd/gen-schemas`" + ` from internal/orchestrator/vocabulary.go — do not edit. -->

# Run Event Types

Every event ` + "`loom run`" + ` writes to ` + "`run-events.jsonl`" + `. This table and
` + "`run-event.schema.json`" + ` are generated from one Go enum, so neither can drift from what the
executor actually emits.

Types that are *specified but emitted by nothing* are deliberately absent — see
` + "`shared/telemetry/README.md`" + ` for that list and the roadmap item that would build each
emitter.

| Kind | Meaning | Fields beyond ` + "`at`" + ` and ` + "`kind`" + ` | Introduced by |
|---|---|---|---|
`
