package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/orieken/loom/internal/orchestrator"
	"github.com/orieken/loom/internal/state"
)

// generate must write one schema per typed stage, so a new state kind
// cannot be added without its schema appearing.
func TestGenerateWritesASchemaPerTypedStage(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "pipeline")
	if err := generate(dir); err != nil {
		t.Fatalf("generate: %v", err)
	}
	for _, schema := range state.StageSchemas() {
		assertValidJSONFile(t, filepath.Join(dir, schema.FileName))
	}
}

// generateTelemetry writes both artifacts, and both are derived from the
// same vocabulary — that is the property that makes them unable to drift
// from each other.
func TestGenerateTelemetryWritesSchemaAndTable(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "telemetry")
	if err := generateTelemetry(dir); err != nil {
		t.Fatalf("generateTelemetry: %v", err)
	}
	assertValidJSONFile(t, filepath.Join(dir, orchestrator.RunEventSchemaFile))

	table, err := os.ReadFile(filepath.Join(dir, orchestrator.RunEventTableFile))
	if err != nil {
		t.Fatalf("read table: %v", err)
	}
	if !strings.Contains(string(table), "GENERATED by") {
		t.Error("table carries no generated-file warning; someone will hand-edit it")
	}
	for _, kind := range orchestrator.EventKindStrings() {
		if !strings.Contains(string(table), "`"+kind+"`") {
			t.Errorf("generated table omits event kind %q", kind)
		}
	}
}

// A directory that cannot be created must fail loudly rather than silently
// writing nothing.
func TestGenerateTelemetryFailsOnAnUnusableDirectory(t *testing.T) {
	blocked := filepath.Join(t.TempDir(), "blocker")
	if err := os.WriteFile(blocked, []byte("not a directory"), 0o644); err != nil {
		t.Fatalf("create blocker: %v", err)
	}
	if err := generateTelemetry(filepath.Join(blocked, "telemetry")); err == nil {
		t.Error("generateTelemetry succeeded against an unusable path")
	}
}

func assertValidJSONFile(t *testing.T, path string) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var decoded map[string]any
	if err := json.Unmarshal(raw, &decoded); err != nil {
		t.Errorf("%s is not valid JSON: %v", path, err)
	}
}
