#!/usr/bin/env bash
# generate-codemap.sh — produce CODEMAP.md at the repo root.
#
# Emits a depth-2 directory tree with a one-line purpose per directory, sourced
# from the directory's README.md first line (stripped of leading # and whitespace).
# Directories with no README get a TODO placeholder.
#
# This is the entry-point document for LLM clients doing Grep/Glob over source:
# read CODEMAP.md first to orient, then use Grep/Glob for specifics.
# See ADR-002 (docs/adrs/ADR-002-corpus-aware-retrieval-strategy.md) — "source
# code tier is deferred per ADR-002; CODEMAP improves it without un-deferring it."
#
# Usage: bash scripts/generate-codemap.sh [--dry-run]
# Written for bash 3.2 (macOS default): no associative arrays, no process substitution
# that relies on 4.x features.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="$REPO_DIR/CODEMAP.md"
DRY_RUN=false
for arg in "$@"; do [[ "$arg" == "--dry-run" ]] && DRY_RUN=true; done

# Extract the first meaningful line from a README (strip leading #, whitespace, blank lines)
readme_purpose() {
  local readme="$1"
  if [[ ! -f "$readme" ]]; then
    echo "TODO — add README.md with a one-line purpose description"
    return
  fi
  local line
  while IFS= read -r line; do
    # skip blank lines
    [[ -z "${line// }" ]] && continue
    # strip leading markdown heading markers and surrounding whitespace
    line="${line#\#\#\#}"
    line="${line#\#\#}"
    line="${line#\#}"
    line="${line# }"
    [[ -n "$line" ]] && echo "$line" && return
  done < "$readme"
  echo "TODO — README.md present but no readable first line"
}

# Build the CODEMAP content
build_codemap() {
  echo "# CODEMAP"
  echo ""
  echo "Entry-point map for LLM Grep/Glob over this repository. Read this before"
  echo "running Grep/Glob to orient to directory purposes; follow with targeted"
  echo "searches rather than scanning the whole tree."
  echo ""
  echo "Generated by \`scripts/generate-codemap.sh\` — regenerate after structural changes."
  echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "## Root"
  echo ""
  readme_purpose "$REPO_DIR/README.md" | sed 's/^/> /'
  echo ""
  echo "## Top-level directories"
  echo ""

  # Walk depth-1 directories (skip hidden, skip symlinks that are just .claude pointers)
  while IFS= read -r dir; do
    name="$(basename "$dir")"
    # Skip .git and other hidden dirs
    [[ "$name" == .* ]] && continue
    # Skip non-directories
    [[ ! -d "$dir" ]] && continue
    purpose="$(readme_purpose "$dir/README.md")"
    echo "### \`$name/\`"
    echo ""
    echo "$purpose"
    echo ""

    # Depth-2 subdirectories
    has_subdirs=false
    while IFS= read -r subdir; do
      subname="$(basename "$subdir")"
      [[ "$subname" == .* ]] && continue
      [[ ! -d "$subdir" ]] && continue
      if ! $has_subdirs; then
        echo "| Subdirectory | Purpose |"
        echo "|---|---|"
        has_subdirs=true
      fi
      subpurpose="$(readme_purpose "$subdir/README.md")"
      echo "| \`$subname/\` | $subpurpose |"
    done < <(find "$dir" -mindepth 1 -maxdepth 1 -type d | sort)
    $has_subdirs && echo ""

  done < <(find "$REPO_DIR" -mindepth 1 -maxdepth 1 -type d | sort)
}

if $DRY_RUN; then
  build_codemap
else
  build_codemap > "$OUTPUT"
  echo "CODEMAP.md written to $OUTPUT"
fi
